### ISSUE TITLE
Moment is no longer an optional dependency

### ISSUE THREAD

**Issue by mickelus** [Pikaday/Pikaday#814]
After updating from 1.7.0 to 1.8.0 we are no longer able to use pikaday without having moment installed. Is moment still indended as an optional dependency?

We get the following error in our webpack build: 
> WARNING in ./node_modules/pikaday/pikaday.js
> Module not found: Error: Can't resolve 'moment' in '$project/node_modules/pikaday'
> @ ./node_modules/pikaday/pikaday.js`

In our grunt/browserify build we get this error:
> Running "browserify:release" (browserify) task
> Error: Cannot find module 'moment' from '/node_modules/pikaday'

**Comment by niksajanjic** [comment]
And if this is not the bug but intentional change, then this is a breaking change and it should be labeled as 2.0 version.

**Comment by wojciechczerniak** [comment]
I see a warning, not an error. 

In my test Webpack output is created correctly, without moment.js. With 1.8.0 you can ignore the warning or install moment.js. If you choose to install moment.js it will be included in the output and an optional dependency is met. When I switch back to 1.7.0 the moment.js is always installed and always included in the output file. 

So now it's finally an optional dependency. Looks how it should work from the very beginning.

**Comment by saltcod** [comment]
https://github.com/Pikaday/Pikaday/issues/718#issuecomment-334749922

^ worked for me.

**Comment by schoenkaft** [comment]
For Browserify, the only option I could find is running it with the `--ignore-missing` flag. To specify this in your config: `ignoreMissing: true`.

This will allow optional dependencies in a `try/catch` block to throw an exception without failing your build.

Depending on your setup this could be safe or unsafe (think of a production build needing to fail in a case like this). In my case it's safe, since any unresolved imports are caught early by ESLint (rule: `import/no-unresolved`).

**Comment by niksajanjic** [comment]
@schoenkaft Thanks for the idea, I have been using browserify and in case you don't have that flag, the build would fail.

Nevertheless, I still think this is a bug. If your code doesn't depend on moment.js there should be no error/warning whatsoever. Also, as @schoenkaft said, that flag is only a partial solution, because it can produce unsafe builds and shouldn't be considered a proper solution.

**Comment by x1c0** [comment]
Same warning here building with Angular CLI: 7.0.2 / Node: 9.0.0 / Angular: 7.0.0

**Comment by niksajanjic** [comment]
After further investigation I realized this is an issue with `browserify`:
https://github.com/browserify/browserify/issues/901

Therefore, as far as build from `browserify` goes, this isn't an issue of `Pikaday`. As a matter of fact, there is a try/catch inside `Pikaday`'s source code that doesn't throw any errors or warnings, so this seems like an issue of build tools that we have been reported here.

**Comment by wojciechczerniak** [comment]
Duplicate of #815
